using System.Data;
using System.Text;
using System.Text.RegularExpressions;
using Universal_Data_Converter.Models;
using Universal_Data_Converter.Services.Analysis;

namespace Universal_Data_Converter.Services.Sql
{
    public class MySqlExporter : ISqlDialectExporter
    {
        private readonly TableAnalyzer _analyzer;

        public MySqlExporter()
        {
            _analyzer = new TableAnalyzer();
        }

        public async Task ExportAsync(DataTable dt, ConversionOptions options)
        {
            if (dt == null) throw new ArgumentNullException(nameof(dt));
            if (options == null) throw new ArgumentNullException(nameof(options));
            if (string.IsNullOrWhiteSpace(options.OutputFile))
                throw new ArgumentException("Output file path is required", nameof(options));

            var analysis = _analyzer.Analyze(dt);

            // Garantir que o diretório de saída existe
            var outputDir = Path.GetDirectoryName(options.OutputFile);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            await using var writer = new StreamWriter(options.OutputFile, false, Encoding.UTF8);

            await WriteHeaderAsync(writer, options);
            await WriteCreateTableStatementAsync(writer, dt, analysis, options);
            await WriteInsertStatementsAsync(writer, dt, options);
            await WriteIndexesAsync(writer, analysis, options);

            await writer.FlushAsync();
        }

        private async Task WriteHeaderAsync(StreamWriter writer, ConversionOptions options)
        {
            await writer.WriteLineAsync("-- ----------------------------------------------------------------------");
            await writer.WriteLineAsync($"-- MySQL dump generated by Universal Data Converter");
            await writer.WriteLineAsync($"-- Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            await writer.WriteLineAsync($"-- Table: {options.SqlTableName}");
            await writer.WriteLineAsync("-- ----------------------------------------------------------------------");
            await writer.WriteLineAsync();

            await writer.WriteLineAsync("SET FOREIGN_KEY_CHECKS = 0;");
            await writer.WriteLineAsync("SET UNIQUE_CHECKS = 0;");
            await writer.WriteLineAsync("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';");
            await writer.WriteLineAsync();
        }

        private async Task WriteCreateTableStatementAsync(StreamWriter writer, DataTable dt, TableAnalysis analysis, ConversionOptions options)
        {
            await writer.WriteLineAsync($"-- Table structure for table `{SanitizeIdentifier(options.SqlTableName)}`");
            await writer.WriteLineAsync($"DROP TABLE IF EXISTS `{SanitizeIdentifier(options.SqlTableName)}`;");
            await writer.WriteLineAsync();

            await writer.WriteLineAsync($"CREATE TABLE `{SanitizeIdentifier(options.SqlTableName)}` (");

            var columnDefinitions = new List<string>();
            var identityColumn = "";

            foreach (DataColumn col in dt.Columns)
            {
                var columnName = SanitizeIdentifier(col.ColumnName);
                var sqlType = MapToMySqlType(col.DataType, col.ColumnName);
                var nullable = analysis.RequiredColumns.Contains(col.ColumnName) ? "NOT NULL" : "NULL";

                var columnDefinition = $"  `{columnName}` {sqlType} {nullable}";

                // Adicionar DEFAULT se existir
                var defaultValue = GetDefaultValue(col);
                if (!string.IsNullOrEmpty(defaultValue))
                {
                    columnDefinition += $" DEFAULT {defaultValue}";
                }

                // Adicionar AUTO_INCREMENT para colunas de identidade
                if (analysis.IdentityColumns.Contains(col.ColumnName) || col.AutoIncrement)
                {
                    columnDefinition += " AUTO_INCREMENT";
                    identityColumn = columnName;
                }

                columnDefinitions.Add(columnDefinition);
            }

            // Adicionar chave primária (se houver)
            if (analysis.PrimaryKeyColumns.Any())
            {
                var pkColumns = analysis.PrimaryKeyColumns.Select(c => $"`{SanitizeIdentifier(c)}`");
                columnDefinitions.Add($"  PRIMARY KEY ({string.Join(", ", pkColumns)})");
            }

            await writer.WriteLineAsync(string.Join(",\n", columnDefinitions));

            // Adicionar opções da tabela
            await writer.WriteLineAsync($") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
            await writer.WriteLineAsync();
        }

        private async Task WriteInsertStatementsAsync(StreamWriter writer, DataTable dt, ConversionOptions options)
        {
            if (dt.Rows.Count == 0) return;

            await writer.WriteLineAsync($"-- Data for table `{SanitizeIdentifier(options.SqlTableName)}`");

            var columns = dt.Columns.Cast<DataColumn>()
                .Select(c => $"`{SanitizeIdentifier(c.ColumnName)}`");

            var insertHeader = $"INSERT INTO `{SanitizeIdentifier(options.SqlTableName)}` ({string.Join(", ", columns)}) VALUES";
            await writer.WriteLineAsync(insertHeader);

            // Processar em lotes para melhor performance
            var batchSize = 100;
            for (int i = 0; i < dt.Rows.Count; i += batchSize)
            {
                var batchRows = dt.Rows.Cast<DataRow>().Skip(i).Take(batchSize).ToList();
                var valuesList = new List<string>();

                foreach (var row in batchRows)
                {
                    var rowValues = new List<string>();
                    foreach (DataColumn col in dt.Columns)
                    {
                        var value = row[col];
                        rowValues.Add(FormatMySqlValue(value, col.DataType));
                    }
                    valuesList.Add($"({string.Join(", ", rowValues)})");
                }

                var separator = i + batchSize >= dt.Rows.Count ? ";" : ",";
                await writer.WriteLineAsync(string.Join(",\n", valuesList) + separator);
            }

            await writer.WriteLineAsync();
        }

        private async Task WriteIndexesAsync(StreamWriter writer, TableAnalysis analysis, ConversionOptions options)
        {
            // Adicionar índices únicos
            foreach (var uniqueCol in analysis.UniqueColumns)
            {
                // Verificar se não é uma PK (PK já é um índice)
                if (!analysis.PrimaryKeyColumns.Contains(uniqueCol))
                {
                    var indexName = $"idx_unique_{SanitizeIdentifier(uniqueCol)}";
                    await writer.WriteLineAsync($"-- Creating unique index on `{SanitizeIdentifier(uniqueCol)}`");
                    await writer.WriteLineAsync($"CREATE UNIQUE INDEX `{indexName}` ON `{SanitizeIdentifier(options.SqlTableName)}` (`{SanitizeIdentifier(uniqueCol)}`);");
                }
            }

            // Criar índices sugeridos
            foreach (var indexCol in analysis.SuggestedIndexes)
            {
                // Verificar se já não é uma PK ou Unique
                if (!analysis.PrimaryKeyColumns.Contains(indexCol) && !analysis.UniqueColumns.Contains(indexCol))
                {
                    var indexName = $"idx_{SanitizeIdentifier(indexCol)}";
                    await writer.WriteLineAsync($"-- Creating suggested index on `{SanitizeIdentifier(indexCol)}`");
                    await writer.WriteLineAsync($"CREATE INDEX `{indexName}` ON `{SanitizeIdentifier(options.SqlTableName)}` (`{SanitizeIdentifier(indexCol)}`);");
                }
            }

            if (analysis.SuggestedIndexes.Any() || analysis.UniqueColumns.Any())
            {
                await writer.WriteLineAsync();
            }

            await writer.WriteLineAsync("SET FOREIGN_KEY_CHECKS = 1;");
            await writer.WriteLineAsync("SET UNIQUE_CHECKS = 1;");
        }

        private string MapToMySqlType(Type dataType, string columnName)
        {
            // Mapear tipos .NET para tipos MySQL apropriados
            if (dataType == typeof(string) || dataType == typeof(char))
            {
                return "TEXT"; // Usar TEXT por padrão para strings
            }

            if (dataType == typeof(int)) return "INT";
            if (dataType == typeof(short)) return "SMALLINT";
            if (dataType == typeof(long)) return "BIGINT";
            if (dataType == typeof(byte)) return "TINYINT";

            if (dataType == typeof(decimal)) return "DECIMAL(18,6)";
            if (dataType == typeof(double)) return "DOUBLE";
            if (dataType == typeof(float)) return "FLOAT";

            if (dataType == typeof(DateTime)) return "DATETIME";
            if (dataType == typeof(bool)) return "TINYINT(1)";
            if (dataType == typeof(byte[])) return "LONGBLOB";
            if (dataType == typeof(Guid)) return "CHAR(36)";

            return "VARCHAR(255)";
        }

        private string? GetDefaultValue(DataColumn column)
        {
            if (column.DefaultValue == null || column.DefaultValue == DBNull.Value)
                return null;

            return FormatMySqlValue(column.DefaultValue, column.DataType);
        }

        private string FormatMySqlValue(object? value, Type dataType)
        {
            if (value == null || value == DBNull.Value)
                return "NULL";

            if (dataType == typeof(string) || dataType == typeof(char))
            {
                string? stringValue = value.ToString();
                return stringValue != null ? $"'{EscapeMySqlString(stringValue)}'" : "NULL";
            }

            if (dataType == typeof(DateTime))
            {
                var date = (DateTime)value;
                return $"'{date:yyyy-MM-dd HH:mm:ss}'";
            }

            if (dataType == typeof(bool))
                return (bool)value ? "1" : "0";

            if (dataType == typeof(byte[]))
            {
                var bytes = (byte[])value;
                return bytes.Length > 0 ? $"0x{BitConverter.ToString(bytes).Replace("-", "")}" : "NULL";
            }

            if (dataType == typeof(Guid))
                return $"'{value}'";

            if (dataType == typeof(decimal) || dataType == typeof(double) || dataType == typeof(float))
            {
                string? numberValue = value.ToString();
                return numberValue?.Replace(",", ".") ?? "NULL";
            }

            // Números inteiros e outros tipos
            return value.ToString() ?? "NULL";
        }

        private string EscapeMySqlString(string? input)
        {
            if (string.IsNullOrEmpty(input))
                return string.Empty;

            return input
                .Replace("\\", "\\\\")
                .Replace("'", "\\'")
                .Replace("\"", "\\\"")
                .Replace("\0", "\\0")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r")
                .Replace("\t", "\\t")
                .Replace("\x1a", "\\Z");
        }

        private string SanitizeIdentifier(string? identifier)
        {
            if (string.IsNullOrEmpty(identifier))
                return "column";

            // Remover caracteres inválidos para identificadores MySQL
            var invalidChars = new[] { '`', '\'', '"', ';', ' ', '-', '.', '/' };
            foreach (var c in invalidChars)
            {
                identifier = identifier.Replace(c.ToString(), "_");
            }

            // Remover caracteres não-ASCII
            identifier = Regex.Replace(identifier, @"[^\w@#\$]", "_");

            // Garantir que não começa com número
            if (identifier.Length > 0 && char.IsDigit(identifier[0]))
                identifier = "_" + identifier;

            return identifier;
        }
    }
}