using System.Data;
using System.Text;
using System.Text.RegularExpressions;
using Universal_Data_Converter.Models;
using Universal_Data_Converter.Services.Analysis;

namespace Universal_Data_Converter.Services.Sql
{
    public class MySqlExporter : ISqlDialectExporter
    {
        private readonly TableAnalyzer _analyzer;

        public MySqlExporter()
        {
            _analyzer = new TableAnalyzer();
        }

        public async Task ExportAsync(DataTable dt, ConversionOptions options)
        {
            if (dt == null) throw new ArgumentNullException(nameof(dt));
            if (options == null) throw new ArgumentNullException(nameof(options));
            if (string.IsNullOrWhiteSpace(options.OutputFile))
                throw new ArgumentException("Output file path is required", nameof(options));

            var analysis = _analyzer.Analyze(dt);

            // Garantir que o diretório de saída existe
            var outputDir = Path.GetDirectoryName(options.OutputFile);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            await using var writer = new StreamWriter(options.OutputFile, false, Encoding.UTF8);

            await WriteHeaderAsync(writer, options);
            await WriteCreateTableStatementAsync(writer, dt, analysis, options);
            await WriteInsertStatementsAsync(writer, dt, options);
            await WriteIndexesAsync(writer, dt, analysis, options);

            await writer.FlushAsync();
        }

        private async Task WriteHeaderAsync(StreamWriter writer, ConversionOptions options)
        {
            await writer.WriteLineAsync("-- ----------------------------------------------------------------------");
            await writer.WriteLineAsync($"-- MySQL dump generated by Universal Data Converter");
            await writer.WriteLineAsync($"-- Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            await writer.WriteLineAsync($"-- Table: {SanitizeIdentifier(options.SqlTableName)}");
            await writer.WriteLineAsync("-- ----------------------------------------------------------------------");
            await writer.WriteLineAsync();

            await writer.WriteLineAsync("SET FOREIGN_KEY_CHECKS = 0;");
            await writer.WriteLineAsync("SET UNIQUE_CHECKS = 0;");
            await writer.WriteLineAsync("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';");
            await writer.WriteLineAsync();
        }

        private async Task WriteCreateTableStatementAsync(StreamWriter writer, DataTable dt, TableAnalysis analysis, ConversionOptions options)
        {
            await writer.WriteLineAsync($"-- Table structure for table `{SanitizeIdentifier(options.SqlTableName)}`");
            await writer.WriteLineAsync($"DROP TABLE IF EXISTS `{SanitizeIdentifier(options.SqlTableName)}`;");
            await writer.WriteLineAsync();

            await writer.WriteLineAsync($"CREATE TABLE `{SanitizeIdentifier(options.SqlTableName)}` (");

            var columnDefinitions = new List<string>();

            foreach (DataColumn col in dt.Columns)
            {
                var columnName = SanitizeIdentifier(col.ColumnName);
                var sqlType = MapToMySqlType(col.DataType, col.ColumnName, dt);
                var nullable = analysis.RequiredColumns.Contains(col.ColumnName) ? "NOT NULL" : "NULL";

                var columnDefinition = $"  `{columnName}` {sqlType} {nullable}";

                // Adicionar DEFAULT se existir
                var defaultValue = GetDefaultValue(col);
                if (!string.IsNullOrEmpty(defaultValue))
                {
                    columnDefinition += $" DEFAULT {defaultValue}";
                }

                // Adicionar AUTO_INCREMENT para colunas de identidade
                if (analysis.IdentityColumns.Contains(col.ColumnName) || col.AutoIncrement)
                {
                    columnDefinition += " AUTO_INCREMENT";
                }

                columnDefinitions.Add(columnDefinition);
            }

            // Adicionar chave primária (se houver)
            if (analysis.PrimaryKeyColumns.Any())
            {
                var pkColumns = analysis.PrimaryKeyColumns.Select(c => $"`{SanitizeIdentifier(c)}`");
                columnDefinitions.Add($"  PRIMARY KEY ({string.Join(", ", pkColumns)})");
            }

            await writer.WriteLineAsync(string.Join(",\n", columnDefinitions));

            // Adicionar opções da tabela
            await writer.WriteLineAsync($") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
            await writer.WriteLineAsync();
        }

        private async Task WriteInsertStatementsAsync(StreamWriter writer, DataTable dt, ConversionOptions options)
        {
            if (dt.Rows.Count == 0) return;

            await writer.WriteLineAsync($"-- Data for table `{SanitizeIdentifier(options.SqlTableName)}`");

            var columns = dt.Columns.Cast<DataColumn>()
                .Select(c => $"`{SanitizeIdentifier(c.ColumnName)}`");

            var insertHeader = $"INSERT INTO `{SanitizeIdentifier(options.SqlTableName)}` ({string.Join(", ", columns)}) VALUES";
            await writer.WriteLineAsync(insertHeader);

            // Processar em lotes para melhor performance
            var batchSize = 100;
            var valuesBatch = new List<string>();

            for (int i = 0; i < dt.Rows.Count; i++)
            {
                var row = dt.Rows[i];
                var rowValues = new List<string>();

                foreach (DataColumn col in dt.Columns)
                {
                    var value = row[col];
                    rowValues.Add(FormatMySqlValue(value, col.DataType));
                }

                valuesBatch.Add($"({string.Join(", ", rowValues)})");

                // Escrever em lotes para evitar memória excessiva
                if (valuesBatch.Count >= batchSize || i == dt.Rows.Count - 1)
                {
                    var separator = (i == dt.Rows.Count - 1) ? ";" : ",";
                    await writer.WriteLineAsync(string.Join(",\n", valuesBatch) + separator);
                    valuesBatch.Clear();
                }
            }

            await writer.WriteLineAsync();
        }

        private async Task WriteIndexesAsync(StreamWriter writer, DataTable dt, TableAnalysis analysis, ConversionOptions options)
        {
            // Conjunto para rastrear índices já criados (evitar duplicatas)
            var createdIndexes = new HashSet<string>();

            // 1. Primeiro, criar índices únicos APENAS para colunas que realmente podem ser únicas
            foreach (var uniqueCol in analysis.UniqueColumns)
            {
                // Verificar se não é uma PK (PK já é um índice)
                if (!analysis.PrimaryKeyColumns.Contains(uniqueCol))
                {
                    // Verificar se a coluna pode ter índice único (não deve ser TEXT longa)
                    if (CanHaveUniqueIndex(dt, uniqueCol))
                    {
                        var indexName = $"idx_unique_{SanitizeIdentifier(uniqueCol)}";
                        if (!createdIndexes.Contains(indexName))
                        {
                            await writer.WriteLineAsync($"-- Creating unique index on `{SanitizeIdentifier(uniqueCol)}`");
                            await writer.WriteLineAsync($"CREATE UNIQUE INDEX `{indexName}` ON `{SanitizeIdentifier(options.SqlTableName)}` (`{SanitizeIdentifier(uniqueCol)}`);");
                            createdIndexes.Add(indexName);
                        }
                    }
                    else
                    {
                        // Se não pode ser única, criar apenas um índice normal
                        await writer.WriteLineAsync($"-- Warning: Column `{uniqueCol}` marked as unique but contains non-unique or long text data. Creating regular index instead.");
                        var indexName = $"idx_{SanitizeIdentifier(uniqueCol)}";
                        if (!createdIndexes.Contains(indexName))
                        {
                            await writer.WriteLineAsync($"CREATE INDEX `{indexName}` ON `{SanitizeIdentifier(options.SqlTableName)}` (`{SanitizeIdentifier(uniqueCol)}`(255));");
                            createdIndexes.Add(indexName);
                        }
                    }
                }
            }

            // 2. Criar índices sugeridos (apenas para colunas que ainda não têm índice)
            foreach (var indexCol in analysis.SuggestedIndexes)
            {
                // Verificar se já não é uma PK ou já tem índice único
                if (!analysis.PrimaryKeyColumns.Contains(indexCol) && !analysis.UniqueColumns.Contains(indexCol))
                {
                    var indexName = $"idx_{SanitizeIdentifier(indexCol)}";
                    if (!createdIndexes.Contains(indexName))
                    {
                        // Verificar o tipo de dados para decidir se precisa de prefixo
                        if (NeedsPrefixIndex(dt, indexCol))
                        {
                            await writer.WriteLineAsync($"-- Creating index on `{SanitizeIdentifier(indexCol)}` (first 255 chars)");
                            await writer.WriteLineAsync($"CREATE INDEX `{indexName}` ON `{SanitizeIdentifier(options.SqlTableName)}` (`{SanitizeIdentifier(indexCol)}`(255));");
                        }
                        else
                        {
                            await writer.WriteLineAsync($"-- Creating index on `{SanitizeIdentifier(indexCol)}`");
                            await writer.WriteLineAsync($"CREATE INDEX `{indexName}` ON `{SanitizeIdentifier(options.SqlTableName)}` (`{SanitizeIdentifier(indexCol)}`);");
                        }
                        createdIndexes.Add(indexName);
                    }
                }
            }

            if (createdIndexes.Any())
            {
                await writer.WriteLineAsync();
            }

            await writer.WriteLineAsync("SET FOREIGN_KEY_CHECKS = 1;");
            await writer.WriteLineAsync("SET UNIQUE_CHECKS = 1;");
        }

        private bool CanHaveUniqueIndex(DataTable dt, string columnName)
        {
            var col = dt.Columns[columnName];
            if (col == null) return false;

            // Colunas não-string podem ter índice único
            if (col.DataType != typeof(string) && col.DataType != typeof(char))
                return true;

            // Para colunas string, verificar se todos os valores são únicos e não muito longos
            var values = new HashSet<string>();
            var maxLength = 0;

            foreach (DataRow row in dt.Rows)
            {
                var value = row[columnName]?.ToString() ?? "";

                if (value.Length > maxLength)
                    maxLength = value.Length;

                // Se encontrar duplicata, não pode ser única
                if (values.Contains(value))
                    return false;

                values.Add(value);
            }

            // MySQL tem limite de 3072 bytes para índices únicos em InnoDB
            // 255 caracteres é um limite seguro para UTF8MB4
            return maxLength <= 255;
        }

        private bool NeedsPrefixIndex(DataTable dt, string columnName)
        {
            var col = dt.Columns[columnName];
            if (col == null) return false;

            // Apenas colunas string precisam de prefixo se forem muito longas
            if (col.DataType != typeof(string) && col.DataType != typeof(char))
                return false;

            var maxLength = 0;
            foreach (DataRow row in dt.Rows)
            {
                var value = row[columnName]?.ToString();
                if (value != null && value.Length > maxLength)
                    maxLength = value.Length;
            }

            // Se o comprimento máximo for maior que 255, precisa de prefixo
            return maxLength > 255;
        }

        private string MapToMySqlType(Type dataType, string columnName, DataTable dt)
        {
            // Mapear tipos .NET para tipos MySQL apropriados
            if (dataType == typeof(string) || dataType == typeof(char))
            {
                // Verificar o comprimento máximo da coluna para decidir entre VARCHAR e TEXT
                var maxLength = 0;
                foreach (DataRow row in dt.Rows)
                {
                    var val = row[columnName]?.ToString();
                    if (val != null && val.Length > maxLength)
                        maxLength = val.Length;
                }

                if (maxLength < 256)
                    return $"VARCHAR({(maxLength > 0 ? maxLength : 255)})";
                else if (maxLength < 65536)
                    return "TEXT";
                else if (maxLength < 16777216)
                    return "MEDIUMTEXT";
                else
                    return "LONGTEXT";
            }

            if (dataType == typeof(int)) return "INT";
            if (dataType == typeof(short)) return "SMALLINT";
            if (dataType == typeof(long)) return "BIGINT";
            if (dataType == typeof(byte)) return "TINYINT";

            if (dataType == typeof(decimal)) return "DECIMAL(18,6)";
            if (dataType == typeof(double)) return "DOUBLE";
            if (dataType == typeof(float)) return "FLOAT";

            if (dataType == typeof(DateTime)) return "DATETIME";
            if (dataType == typeof(bool)) return "TINYINT(1)";
            if (dataType == typeof(byte[])) return "LONGBLOB";
            if (dataType == typeof(Guid)) return "CHAR(36)";

            return "VARCHAR(255)";
        }

        private string? GetDefaultValue(DataColumn column)
        {
            if (column.DefaultValue == null || column.DefaultValue == DBNull.Value)
                return null;

            return FormatMySqlValue(column.DefaultValue, column.DataType);
        }

        private string FormatMySqlValue(object? value, Type dataType)
        {
            if (value == null || value == DBNull.Value)
                return "NULL";

            if (dataType == typeof(string) || dataType == typeof(char))
            {
                string? stringValue = value.ToString();
                return stringValue != null ? $"'{EscapeMySqlString(stringValue)}'" : "NULL";
            }

            if (dataType == typeof(DateTime))
            {
                var date = (DateTime)value;
                return $"'{date:yyyy-MM-dd HH:mm:ss}'";
            }

            if (dataType == typeof(bool))
                return (bool)value ? "1" : "0";

            if (dataType == typeof(byte[]))
            {
                var bytes = (byte[])value;
                return bytes.Length > 0 ? $"0x{BitConverter.ToString(bytes).Replace("-", "")}" : "NULL";
            }

            if (dataType == typeof(Guid))
                return $"'{value}'";

            if (dataType == typeof(decimal) || dataType == typeof(double) || dataType == typeof(float))
            {
                string? numberValue = value.ToString();
                return numberValue?.Replace(",", ".") ?? "NULL";
            }

            // Números inteiros e outros tipos
            return value.ToString() ?? "NULL";
        }

        private string EscapeMySqlString(string? input)
        {
            if (string.IsNullOrEmpty(input))
                return string.Empty;

            return input
                .Replace("\\", "\\\\")
                .Replace("'", "\\'")
                .Replace("\"", "\\\"")
                .Replace("\0", "\\0")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r")
                .Replace("\t", "\\t")
                .Replace("\x1a", "\\Z");
        }

        private string SanitizeIdentifier(string? identifier)
        {
            if (string.IsNullOrEmpty(identifier))
                return "column";

            // Remover caracteres inválidos para identificadores MySQL
            var invalidChars = new[] { '`', '\'', '"', ';', ' ', '-', '.', '/' };
            foreach (var c in invalidChars)
            {
                identifier = identifier.Replace(c.ToString(), "_");
            }

            // Remover caracteres não-ASCII
            identifier = Regex.Replace(identifier, @"[^\w@#\$]", "_");

            // Garantir que não começa com número
            if (identifier.Length > 0 && char.IsDigit(identifier[0]))
                identifier = "_" + identifier;

            return identifier;
        }
    }
}