using System.Data;
using System.Text;
using System.Text.RegularExpressions;
using Universal_Data_Converter.Models;
using Universal_Data_Converter.Services.Analysis;

namespace Universal_Data_Converter.Services.Sql
{
    public class MySqlExporter : ISqlDialectExporter
    {
        private readonly TableAnalyzer _analyzer;

        public MySqlExporter()
        {
            _analyzer = new TableAnalyzer();
        }

        public async Task ExportAsync(DataTable dt, ConversionOptions options)
        {
            if (dt == null) throw new ArgumentNullException(nameof(dt));
            if (options == null) throw new ArgumentNullException(nameof(options));
            if (string.IsNullOrWhiteSpace(options.OutputFile))
                throw new ArgumentException("Output file path is required", nameof(options));

            var analysis = _analyzer.Analyze(dt);

            var outputDir = Path.GetDirectoryName(options.OutputFile);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            await using var writer = new StreamWriter(options.OutputFile, false, Encoding.UTF8);

            await WriteHeaderAsync(writer, options);
            await WriteCreateTableStatementAsync(writer, dt, analysis, options);
            await WriteInsertStatementsAsync(writer, dt, options);
            await WriteIndexesAsync(writer, dt, analysis, options);

            await writer.FlushAsync();
        }

        private async Task WriteHeaderAsync(StreamWriter writer, ConversionOptions options)
        {
            await writer.WriteLineAsync("-- ----------------------------------------------------------------------");
            await writer.WriteLineAsync($"-- MySQL dump generated by Universal Data Converter");
            await writer.WriteLineAsync($"-- Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            await writer.WriteLineAsync($"-- Table: {SanitizeIdentifier(options.SqlTableName)}");
            await writer.WriteLineAsync("-- ----------------------------------------------------------------------");
            await writer.WriteLineAsync();

            await writer.WriteLineAsync("SET FOREIGN_KEY_CHECKS = 0;");
            await writer.WriteLineAsync("SET UNIQUE_CHECKS = 0;");
            await writer.WriteLineAsync("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';");
            await writer.WriteLineAsync();
        }

        private async Task WriteCreateTableStatementAsync(StreamWriter writer, DataTable dt, TableAnalysis analysis, ConversionOptions options)
        {
            await writer.WriteLineAsync($"-- Table structure for table `{SanitizeIdentifier(options.SqlTableName)}`");
            await writer.WriteLineAsync($"DROP TABLE IF EXISTS `{SanitizeIdentifier(options.SqlTableName)}`;");
            await writer.WriteLineAsync();

            await writer.WriteLineAsync($"CREATE TABLE `{SanitizeIdentifier(options.SqlTableName)}` (");

            var columnDefinitions = new List<string>();

            foreach (DataColumn col in dt.Columns)
            {
                var columnName = SanitizeIdentifier(col.ColumnName);
                var sqlType = MapToMySqlType(col.DataType, col.ColumnName, dt);
                var nullable = analysis.RequiredColumns.Contains(col.ColumnName) ? "NOT NULL" : "NULL";

                var columnDefinition = $"  `{columnName}` {sqlType} {nullable}";

                var defaultValue = GetDefaultValue(col);
                if (!string.IsNullOrEmpty(defaultValue))
                {
                    columnDefinition += $" DEFAULT {defaultValue}";
                }

                if (analysis.IdentityColumns.Contains(col.ColumnName) || col.AutoIncrement)
                {
                    columnDefinition += " AUTO_INCREMENT";
                }

                columnDefinitions.Add(columnDefinition);
            }

            if (analysis.PrimaryKeyColumns.Any())
            {
                var pkColumns = analysis.PrimaryKeyColumns.Select(c => $"`{SanitizeIdentifier(c)}`");
                columnDefinitions.Add($"  PRIMARY KEY ({string.Join(", ", pkColumns)})");
            }

            await writer.WriteLineAsync(string.Join(",\n", columnDefinitions));
            await writer.WriteLineAsync($") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
            await writer.WriteLineAsync();
        }

        private async Task WriteInsertStatementsAsync(StreamWriter writer, DataTable dt, ConversionOptions options)
        {
            if (dt.Rows.Count == 0) return;

            await writer.WriteLineAsync($"-- Data for table `{SanitizeIdentifier(options.SqlTableName)}`");

            var columns = dt.Columns.Cast<DataColumn>()
                .Select(c => $"`{SanitizeIdentifier(c.ColumnName)}`");

            var insertHeader = $"INSERT INTO `{SanitizeIdentifier(options.SqlTableName)}` ({string.Join(", ", columns)}) VALUES";
            await writer.WriteLineAsync(insertHeader);

            var batchSize = 100;
            var valuesBatch = new List<string>();

            for (int i = 0; i < dt.Rows.Count; i++)
            {
                var row = dt.Rows[i];
                var rowValues = new List<string>();

                foreach (DataColumn col in dt.Columns)
                {
                    var value = row[col];
                    rowValues.Add(FormatMySqlValue(value, col.DataType));
                }

                valuesBatch.Add($"({string.Join(", ", rowValues)})");

                if (valuesBatch.Count >= batchSize || i == dt.Rows.Count - 1)
                {
                    var separator = (i == dt.Rows.Count - 1) ? ";" : ",";
                    await writer.WriteLineAsync(string.Join(",\n", valuesBatch) + separator);
                    valuesBatch.Clear();
                }
            }

            await writer.WriteLineAsync();
        }

        private async Task WriteIndexesAsync(StreamWriter writer, DataTable dt, TableAnalysis analysis, ConversionOptions options)
        {
            var createdIndexes = new HashSet<string>();
            var actualUniqueColumns = new List<string>();

            // Verificar quais colunas realmente têm valores únicos
            foreach (var uniqueCol in analysis.UniqueColumns)
            {
                if (HasColumnUniqueValues(dt, uniqueCol))
                {
                    actualUniqueColumns.Add(uniqueCol);
                }
            }

            // Criar índices únicos
            foreach (var uniqueCol in actualUniqueColumns)
            {
                if (!analysis.PrimaryKeyColumns.Contains(uniqueCol))
                {
                    if (CanHaveUniqueIndex(dt, uniqueCol))
                    {
                        var indexName = $"idx_unique_{SanitizeIdentifier(uniqueCol)}";
                        if (!createdIndexes.Contains(indexName))
                        {
                            await writer.WriteLineAsync($"-- Creating unique index on `{SanitizeIdentifier(uniqueCol)}`");
                            await writer.WriteLineAsync($"CREATE UNIQUE INDEX `{indexName}` ON `{SanitizeIdentifier(options.SqlTableName)}` (`{SanitizeIdentifier(uniqueCol)}`);");
                            createdIndexes.Add(indexName);
                        }
                    }
                }
            }

            // Criar índices sugeridos
            foreach (var indexCol in analysis.SuggestedIndexes)
            {
                if (!analysis.PrimaryKeyColumns.Contains(indexCol) && !actualUniqueColumns.Contains(indexCol))
                {
                    var indexName = $"idx_{SanitizeIdentifier(indexCol)}";
                    if (!createdIndexes.Contains(indexName))
                    {
                        if (NeedsPrefixIndex(dt, indexCol))
                        {
                            await writer.WriteLineAsync($"-- Creating index on `{SanitizeIdentifier(indexCol)}` (first 255 chars)");
                            await writer.WriteLineAsync($"CREATE INDEX `{indexName}` ON `{SanitizeIdentifier(options.SqlTableName)}` (`{SanitizeIdentifier(indexCol)}`(255));");
                        }
                        else
                        {
                            await writer.WriteLineAsync($"-- Creating index on `{SanitizeIdentifier(indexCol)}`");
                            await writer.WriteLineAsync($"CREATE INDEX `{indexName}` ON `{SanitizeIdentifier(options.SqlTableName)}` (`{SanitizeIdentifier(indexCol)}`);");
                        }
                        createdIndexes.Add(indexName);
                    }
                }
            }

            if (createdIndexes.Any())
            {
                await writer.WriteLineAsync();
            }

            await writer.WriteLineAsync("SET FOREIGN_KEY_CHECKS = 1;");
            await writer.WriteLineAsync("SET UNIQUE_CHECKS = 1;");
        }

        // MÉTODO CORRIGIDO - O mais importante!
        private string FormatMySqlValue(object? value, Type dataType)
        {
            if (value == null || value == DBNull.Value)
                return "NULL";

            // Tratamento especial para strings
            if (dataType == typeof(string) || dataType == typeof(char))
            {
                string? stringValue = value.ToString();
                if (stringValue == null)
                    return "NULL";

                // PASSO 1: Escapar barras invertidas
                string escaped = stringValue.Replace("\\", "\\\\");

                // PASSO 2: DUPLICAR aspas simples (NÃO usar barra invertida)
                // Isso converte ' -> '' que é o padrão SQL
                escaped = escaped.Replace("'", "''");

                return $"'{escaped}'";
            }

            if (dataType == typeof(DateTime))
            {
                var date = (DateTime)value;
                return $"'{date:yyyy-MM-dd HH:mm:ss}'";
            }

            if (dataType == typeof(bool))
                return (bool)value ? "1" : "0";

            if (dataType == typeof(byte[]))
            {
                var bytes = (byte[])value;
                return bytes.Length > 0 ? $"0x{BitConverter.ToString(bytes).Replace("-", "")}" : "NULL";
            }

            if (dataType == typeof(Guid))
                return $"'{value}'";

            if (dataType == typeof(decimal) || dataType == typeof(double) || dataType == typeof(float))
            {
                string? numberValue = value.ToString();
                return numberValue?.Replace(",", ".") ?? "NULL";
            }

            return value.ToString() ?? "NULL";
        }

        // Método auxiliar para verificar valores únicos
        private bool HasColumnUniqueValues(DataTable dt, string columnName)
        {
            var col = dt.Columns[columnName];
            if (col == null) return false;

            var values = new HashSet<string>();

            foreach (DataRow row in dt.Rows)
            {
                var value = row[columnName]?.ToString() ?? "";
                if (values.Contains(value))
                    return false;
                values.Add(value);
            }

            return true;
        }

        private bool CanHaveUniqueIndex(DataTable dt, string columnName)
        {
            var col = dt.Columns[columnName];
            if (col == null) return false;

            if (col.DataType != typeof(string) && col.DataType != typeof(char))
                return true;

            var maxLength = 0;
            foreach (DataRow row in dt.Rows)
            {
                var value = row[columnName]?.ToString() ?? "";
                if (value.Length > maxLength)
                    maxLength = value.Length;
            }

            return maxLength <= 255;
        }

        private bool NeedsPrefixIndex(DataTable dt, string columnName)
        {
            var col = dt.Columns[columnName];
            if (col == null) return false;

            if (col.DataType != typeof(string) && col.DataType != typeof(char))
                return false;

            var maxLength = 0;
            foreach (DataRow row in dt.Rows)
            {
                var value = row[columnName]?.ToString();
                if (value != null && value.Length > maxLength)
                    maxLength = value.Length;
            }

            return maxLength > 255;
        }

        private string MapToMySqlType(Type dataType, string columnName, DataTable dt)
        {
            if (dataType == typeof(string) || dataType == typeof(char))
            {
                var maxLength = 0;
                foreach (DataRow row in dt.Rows)
                {
                    var val = row[columnName]?.ToString();
                    if (val != null && val.Length > maxLength)
                        maxLength = val.Length;
                }

                if (maxLength < 256)
                    return $"VARCHAR({(maxLength > 0 ? maxLength : 255)})";
                else if (maxLength < 65536)
                    return "TEXT";
                else if (maxLength < 16777216)
                    return "MEDIUMTEXT";
                else
                    return "LONGTEXT";
            }

            if (dataType == typeof(int)) return "INT";
            if (dataType == typeof(short)) return "SMALLINT";
            if (dataType == typeof(long)) return "BIGINT";
            if (dataType == typeof(byte)) return "TINYINT";

            if (dataType == typeof(decimal)) return "DECIMAL(18,6)";
            if (dataType == typeof(double)) return "DOUBLE";
            if (dataType == typeof(float)) return "FLOAT";

            if (dataType == typeof(DateTime)) return "DATETIME";
            if (dataType == typeof(bool)) return "TINYINT(1)";
            if (dataType == typeof(byte[])) return "LONGBLOB";
            if (dataType == typeof(Guid)) return "CHAR(36)";

            return "VARCHAR(255)";
        }

        private string? GetDefaultValue(DataColumn column)
        {
            if (column.DefaultValue == null || column.DefaultValue == DBNull.Value)
                return null;

            return FormatMySqlValue(column.DefaultValue, column.DataType);
        }

        private string SanitizeIdentifier(string? identifier)
        {
            if (string.IsNullOrEmpty(identifier))
                return "column";

            var invalidChars = new[] { '`', '\'', '"', ';', ' ', '-', '.', '/' };
            foreach (var c in invalidChars)
            {
                identifier = identifier.Replace(c.ToString(), "_");
            }

            identifier = Regex.Replace(identifier, @"[^\w@#\$]", "_");

            if (identifier.Length > 0 && char.IsDigit(identifier[0]))
                identifier = "_" + identifier;

            return identifier;
        }
    }
}