using System.Data;
using System.Text;
using Universal_Data_Converter.Models;
using Universal_Data_Converter.Services.Analysis;

namespace Universal_Data_Converter.Services.Sql
{
    public class SqliteExporter : ISqlDialectExporter
    {
        public async Task ExportAsync(DataTable dt, ConversionOptions options)
        {
            var analyzer = new TableAnalyzer();
            var analysis = analyzer.Analyze(dt);

            using var writer = new StreamWriter(options.OutputFile, false, Encoding.UTF8);

            writer.WriteLine($"-- ===================================================");
            writer.WriteLine($"-- Generated by Universal Data Converter");
            writer.WriteLine($"-- Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            writer.WriteLine($"-- Source: {options.InputFile}");
            writer.WriteLine($"-- Dialect: SQLite");
            writer.WriteLine($"-- Records: {dt.Rows.Count}");
            writer.WriteLine($"-- ===================================================");
            writer.WriteLine();

            writer.WriteLine($"DROP TABLE IF EXISTS \"{options.SqlTableName}\";");
            writer.WriteLine();

            writer.WriteLine($"CREATE TABLE \"{options.SqlTableName}\" (");

            var columns = new List<string>();

            foreach (DataColumn col in dt.Columns)
            {
                var (type, isPk) = DetectSqliteType(col, dt, analysis);
                var nullable = analysis.RequiredColumns.Contains(col.ColumnName) ? "NOT NULL" : "";

                var escapedColumnName = EscapeSqliteIdentifier(col.ColumnName);

                // Se for PK com AUTOINCREMENT, não adiciona NOT NULL separadamente (já está incluso)
                if (isPk && type.Contains("AUTOINCREMENT"))
                {
                    columns.Add($"  \"{escapedColumnName}\" {type}");
                }
                else
                {
                    columns.Add($"  \"{escapedColumnName}\" {type} {nullable}".Trim());
                }
            }

            // SÓ adiciona PRIMARY KEY separada se NÃO tiver usado PRIMARY KEY na coluna
            if (analysis.PrimaryKeyColumns.Any() && !HasInlinePrimaryKey(analysis))
            {
                var pk = string.Join(", ", analysis.PrimaryKeyColumns.Select(c => $"\"{EscapeSqliteIdentifier(c)}\""));
                columns.Add($"  PRIMARY KEY ({pk})");
            }

            writer.WriteLine(string.Join(",\n", columns));
            writer.WriteLine(");\n");

            writer.WriteLine($"-- Inserindo {dt.Rows.Count} registros");
            await WriteInserts(writer, dt, options);

            writer.WriteLine();
            writer.WriteLine($"-- ===================================================");
            writer.WriteLine($"-- End of SQL script");
            writer.WriteLine($"-- ===================================================");

            await writer.FlushAsync();
        }

        private bool HasInlinePrimaryKey(TableAnalysis analysis)
        {
            // No SQLite, apenas colunas INTEGER PRIMARY KEY podem ser AUTOINCREMENT
            // e devem ser definidas inline
            return analysis.PrimaryKeyColumns.Count == 1 &&
                   analysis.IdentityColumns.Contains(analysis.PrimaryKeyColumns[0]);
        }

        private (string type, bool isPrimaryKey) DetectSqliteType(DataColumn col, DataTable dt, TableAnalysis analysis)
        {
            var isPrimaryKey = analysis.PrimaryKeyColumns.Contains(col.ColumnName);
            var isIdentity = analysis.IdentityColumns.Contains(col.ColumnName);

            // Se for chave primária inteira e identity, usar INTEGER PRIMARY KEY AUTOINCREMENT
            if (isPrimaryKey && isIdentity &&
                (col.DataType == typeof(int) || col.DataType == typeof(long)))
            {
                return ("INTEGER PRIMARY KEY AUTOINCREMENT", true);
            }

            // Se for chave primária mas não identity, usar apenas PRIMARY KEY (será adicionada separadamente)
            if (isPrimaryKey)
            {
                // Retorna o tipo normal, a PK será adicionada no final
                if (col.DataType == typeof(int) || col.DataType == typeof(long))
                    return ("INTEGER", false);
                if (col.DataType == typeof(decimal) || col.DataType == typeof(double) || col.DataType == typeof(float))
                    return ("REAL", false);
                if (col.DataType == typeof(bool))
                    return ("INTEGER", false);
                if (col.DataType == typeof(DateTime))
                    return ("TEXT", false);
                return ("TEXT", false);
            }

            // Colunas normais (não PK)
            if (col.DataType == typeof(int) || col.DataType == typeof(long))
                return ("INTEGER", false);

            if (col.DataType == typeof(decimal) || col.DataType == typeof(double) || col.DataType == typeof(float))
                return ("REAL", false);

            if (col.DataType == typeof(bool))
                return ("INTEGER", false); // SQLite não tem BOOLEAN, usa 0/1

            if (col.DataType == typeof(DateTime))
                return ("TEXT", false); // SQLite não tem DATETIME, armazena como TEXT

            return ("TEXT", false);
        }

        private async Task WriteInserts(StreamWriter writer, DataTable dt, ConversionOptions options)
        {
            var columns = dt.Columns.Cast<DataColumn>().ToList();
            var columnNames = string.Join(", ", columns.Select(c => $"\"{EscapeSqliteIdentifier(c.ColumnName)}\""));

            int batchSize = 500;
            var rows = dt.AsEnumerable().ToList();

            for (int i = 0; i < rows.Count; i += batchSize)
            {
                var batch = rows.Skip(i).Take(batchSize).ToList();
                var valuesList = new List<string>();

                foreach (var row in batch)
                {
                    var values = columns.Select(c => FormatSqliteValue(row[c])).ToList();
                    valuesList.Add($"({string.Join(", ", values)})");
                }

                if (valuesList.Any())
                {
                    await writer.WriteLineAsync($"INSERT INTO \"{options.SqlTableName}\" ({columnNames}) VALUES");
                    await writer.WriteLineAsync(string.Join(",\n", valuesList) + ";");

                    if (i + batchSize < rows.Count)
                        await writer.WriteLineAsync();
                }
            }
        }

        private string FormatSqliteValue(object value)
        {
            if (value == DBNull.Value || value == null)
                return "NULL";

            if (value is DateTime date)
                return $"'{date:yyyy-MM-dd HH:mm:ss}'";

            if (value is bool b)
                return b ? "1" : "0";

            if (value is int || value is long || value is double || value is decimal || value is float)
            {
                return Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture);
            }

            var strValue = value.ToString() ?? "";
            strValue = strValue.Replace("'", "''");

            return $"'{strValue}'";
        }

        private string EscapeSqliteIdentifier(string identifier)
        {
            return identifier.Replace("\"", "\"\"");
        }
    }
}